/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Java_assignment;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZK
 */
public class Modify extends javax.swing.JFrame {

    /**
     * Creates new form Modify
     */
    public Modify() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        ImageIcon logo = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("pic/logo.jpg")));
        Image logo_pic1 = logo.getImage();
        Image logo_pic2 = logo_pic1.getScaledInstance(Logo_pic.getWidth(), Logo_pic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon logo_pic = new ImageIcon(logo_pic2);
        Logo_pic.setIcon(logo_pic);
        
        ImageIcon admin = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("pic/admin.jpg")));
        Image adm_pic1 = admin.getImage();
        Image adm_pic2 = adm_pic1.getScaledInstance(adm_pic.getWidth(), adm_pic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon admin_pic = new ImageIcon(adm_pic2);
        adm_pic.setIcon(admin_pic);
        Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Main_title = new javax.swing.JLabel();
        Logo_pic = new javax.swing.JLabel();
        search_field = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Modify_btn = new javax.swing.JButton();
        ViewR_btn = new javax.swing.JButton();
        Booking_btn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        adm_pic = new javax.swing.JLabel();
        Cus_name = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        checkout = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        receipt = new javax.swing.JButton();
        modify = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ZK Resort Room Booking System");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Main_title.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Main_title.setText("ZK Resort Room Booking System");

        Logo_pic.setBackground(new java.awt.Color(0, 255, 255));
        Logo_pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo_pic.setText("Logo");

        search_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_fieldActionPerformed(evt);
            }
        });

        Search.setText("Search");
        Search.setFocusable(false);
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Logo_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Main_title, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo_pic, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Main_title)
                    .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Modify_btn.setText("Manage");
        Modify_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modify_btnActionPerformed(evt);
            }
        });

        ViewR_btn.setText("View Receipt");
        ViewR_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewR_btnActionPerformed(evt);
            }
        });

        Booking_btn.setText("Booking");
        Booking_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Booking_btnActionPerformed(evt);
            }
        });

        Logout_btn.setText("Logout");
        Logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btnActionPerformed(evt);
            }
        });

        adm_pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adm_pic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Cus_name.setBackground(new java.awt.Color(0, 255, 255));
        Cus_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cus_name.setText("Staff");
        Cus_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cus_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adm_pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Modify_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewR_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(Logout_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(Booking_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adm_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Booking_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Modify_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewR_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        back.setText("Back");
        back.setFocusable(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Sight", "Room ID", "Customer Name", "I/C no/ Passport No.", "Email", "Contact number", "Start Date", "End Date", "Days", "Total Amount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(13);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(15);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(90);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(15);
            jTable1.getColumnModel().getColumn(10).setResizable(false);
            jTable1.getColumnModel().getColumn(10).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(11).setResizable(false);
            jTable1.getColumnModel().getColumn(11).setPreferredWidth(30);
        }

        checkout.setText("checkout");
        checkout.setFocusable(false);
        checkout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutMouseClicked(evt);
            }
        });
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.setFocusable(false);
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        receipt.setText("View Receipt");
        receipt.setFocusable(false);
        receipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receiptMouseClicked(evt);
            }
        });
        receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptActionPerformed(evt);
            }
        });

        modify.setText("Modify");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modify, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receipt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkout)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(checkout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(receipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed
        Index_page ip = new Index_page();
        ip.show();
        dispose();
    }//GEN-LAST:event_Logout_btnActionPerformed

    private void Modify_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modify_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Modify_btnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Main_menu mm = new Main_menu();
        mm.show();
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed

    }//GEN-LAST:event_checkoutActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
    }//GEN-LAST:event_deleteActionPerformed
private JFrame Delete_Frame;
    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        Delete_Frame = new JFrame("Booking");
        int column = jTable1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/jTable1.getRowHeight();
        if(row < jTable1.getRowCount() && row >= 0 && column < jTable1.getColumnCount() && column >= 0){
            Object rowValue = jTable1.getValueAt(row, column);
            DefaultTableModel tableModel = (DefaultTableModel)this.jTable1.getModel();
            String lineToRemove = null;
            int[] selectedRows = jTable1.getSelectedRows();
            for (int i = 0; i< selectedRows.length; i++){
                    //int modelIndex = jTable1.convertRowIndexToModel(selectedRows[i]);
                    String first = jTable1.getModel().getValueAt(selectedRows[i], 1).toString();
                    String second = jTable1.getModel().getValueAt(selectedRows[i], 2).toString();
                    String third = jTable1.getModel().getValueAt(selectedRows[i], 3).toString();
                    String fourth = jTable1.getModel().getValueAt(selectedRows[i], 4).toString();
                    String fifth = jTable1.getModel().getValueAt(selectedRows[i], 5).toString();
                    String sixth = jTable1.getModel().getValueAt(selectedRows[i], 6).toString();
                    String seventh = jTable1.getModel().getValueAt(selectedRows[i], 7).toString();
                    String eighth = jTable1.getModel().getValueAt(selectedRows[i], 8).toString();
                    String ninth = jTable1.getModel().getValueAt(selectedRows[i], 9).toString();
                    String tenth = jTable1.getModel().getValueAt(selectedRows[i], 10).toString();
                    String eleventh = jTable1.getModel().getValueAt(selectedRows[i], 11).toString();
                    lineToRemove = first +", "+ second +", "+ third +", "+ fourth +", "+ fifth +", "+ sixth +", "+ seventh +", "+ eighth +", "+ ninth +", "+ tenth +", "+ eleventh;
                    tableModel.removeRow(selectedRows[i]);
                    //System.out.println(lineToRemove);
            }
                try{
                    File file = new File("file/booking.txt");
                    File tempfile = new File("file/tempbooking.txt");
                    BufferedReader reader = new BufferedReader(new FileReader(file));
                    BufferedWriter writer = new BufferedWriter(new FileWriter(tempfile));

                    String currentLine;
                    while((currentLine = reader.readLine()) != null) {
                        // trim newline when comparing with lineToRemove
                        String trimmedLine = currentLine.trim();
                        if(trimmedLine.equals(lineToRemove)) continue;
                        writer.write(currentLine + System.getProperty("line.separator"));
                    }
                    writer.close(); 
                    reader.close();
                    boolean succeed = file.delete();
                    boolean successful = tempfile.renameTo(file);
                    
                    if (succeed == true){
                        //System.out.println("True");
                    }else{
                        System.out.println("Fail to delete the file");
                    }
                    if (successful == true){
                        //System.out.println("True");
                    }else{
                        System.out.println("Fail to change the name");
                    }
                    Delete_Frame = new JFrame("Delete Complete!");
                    JOptionPane.showMessageDialog( Delete_Frame,"Delete Completed!");
                    //jTable1.repaint();
                    //jTable1.revalidate();
                }catch (Exception e){
                    System.out.print("Delete Line Error");
                    e.printStackTrace();
                } 
            //}   
        }
        jScrollPane1.repaint();
        jScrollPane1.revalidate();
    }//GEN-LAST:event_deleteMouseClicked
private JFrame Checkout_Frame;
    private void checkoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutMouseClicked
        Checkout_Frame = new JFrame("Checkout");
        int column = jTable1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/jTable1.getRowHeight();
        if(row < jTable1.getRowCount() && row >= 0 && column < jTable1.getColumnCount() && column >= 0){
            Object rowValue = jTable1.getValueAt(row, column);
            DefaultTableModel tableModel = (DefaultTableModel)this.jTable1.getModel();
            String lineToRemove = null;
            String lineToAdd = null;
            int[] selectedRows = jTable1.getSelectedRows();
            for (int i = 0; i< selectedRows.length; i++){
                    String first = jTable1.getModel().getValueAt(selectedRows[i], 1).toString();
                    String second = jTable1.getModel().getValueAt(selectedRows[i], 2).toString();
                    String third = jTable1.getModel().getValueAt(selectedRows[i], 3).toString();
                    String fourth = jTable1.getModel().getValueAt(selectedRows[i], 4).toString();
                    String fifth = jTable1.getModel().getValueAt(selectedRows[i], 5).toString();
                    String sixth = jTable1.getModel().getValueAt(selectedRows[i], 6).toString();
                    String seventh = jTable1.getModel().getValueAt(selectedRows[i], 7).toString();
                    String eighth = jTable1.getModel().getValueAt(selectedRows[i], 8).toString();
                    String ninth = jTable1.getModel().getValueAt(selectedRows[i], 9).toString();
                    String tenth = jTable1.getModel().getValueAt(selectedRows[i], 10).toString();
                    String eleventh = jTable1.getModel().getValueAt(selectedRows[i], 11).toString();
                    lineToRemove = first +", "+ second +", "+ third +", "+ fourth +", "+ fifth +", "+ sixth +", "+ seventh +", "+ eighth +", "+ ninth +", "+ tenth +", "+ eleventh;
                    lineToAdd = first +", "+ second +", "+ third +", "+ fourth +", "+ fifth +", "+ sixth +", "+ seventh +", "+ eighth +", "+ ninth +", "+ tenth +", "+ "Completed";  
            }
                try{
                    File file = new File("file/booking.txt");
                    File tempfile = new File("file/tempbooking.txt");
                    BufferedReader reader = new BufferedReader(new FileReader(file));
                    BufferedWriter writer = new BufferedWriter(new FileWriter(tempfile));

                    String currentLine;
                    while((currentLine = reader.readLine()) != null) {
                        String trimmedLine = currentLine.trim();
                        if(trimmedLine.equals(lineToRemove)) continue;
                        writer.write(currentLine + System.getProperty("line.separator"));
                        jTable1.repaint();
                        jTable1.revalidate();
                    }
                    writer.write(lineToAdd);
                    writer.close(); 
                    reader.close();
                    boolean succeed = file.delete();
                    boolean successful = tempfile.renameTo(file);
                    
                    if (succeed == true){
                        //System.out.println("True");
                    }else{
                        System.out.println("Fail to delete the file");
                    }
                    if (successful == true){
                        //System.out.println("True");
                    }else{
                        System.out.println("Fail to change the name");
                    }
                    Checkout_Frame = new JFrame("Checkout Complete!");
                    JOptionPane.showMessageDialog( Checkout_Frame,"Checkout Completed!");
                }catch (Exception e){
                    System.out.print("Delete Line Error");
                    e.printStackTrace();
                }
        }
        jScrollPane1.repaint();
        jScrollPane1.revalidate(); 
    }//GEN-LAST:event_checkoutMouseClicked

    private void receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiptActionPerformed

    private void receiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receiptMouseClicked
       Receipt rc = new Receipt();
        int column = jTable1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/jTable1.getRowHeight();
        if(row < jTable1.getRowCount() && row >= 0 && column < jTable1.getColumnCount() && column >= 0){
            Object rowValue = jTable1.getValueAt(row, column);
            DefaultTableModel tableModel = (DefaultTableModel)this.jTable1.getModel();
            String lineToView = null;
            int[] selectedRows = jTable1.getSelectedRows();
            for (int i = 0; i< selectedRows.length; i++){
                    String first = jTable1.getModel().getValueAt(selectedRows[i], 1).toString();
                    String second = jTable1.getModel().getValueAt(selectedRows[i], 2).toString();
                    String third = jTable1.getModel().getValueAt(selectedRows[i], 3).toString();
                    String fourth = jTable1.getModel().getValueAt(selectedRows[i], 4).toString();
                    String fifth = jTable1.getModel().getValueAt(selectedRows[i], 5).toString();
                    String sixth = jTable1.getModel().getValueAt(selectedRows[i], 6).toString();
                    String seventh = jTable1.getModel().getValueAt(selectedRows[i], 7).toString();
                    String eighth = jTable1.getModel().getValueAt(selectedRows[i], 8).toString();
                    String ninth = jTable1.getModel().getValueAt(selectedRows[i], 9).toString();
                    String tenth = jTable1.getModel().getValueAt(selectedRows[i], 10).toString();
                    String eleventh = jTable1.getModel().getValueAt(selectedRows[i], 11).toString();
                    lineToView = first +", "+ second +", "+ third +", "+ fourth +", "+ fifth +", "+ sixth +", "+ seventh +", "+ eighth +", "+ ninth +", "+ tenth +", "+ eleventh;
                    rc.Sight.setText(first);
                    rc.Room_Price.setText("RM 350");
                    rc.Room_No.setText(second);
                    rc.name.setText(third);
                    rc.ic.setText(fourth);
                    rc.email.setText(fifth);
                    rc.contacts.setText(sixth);
                    rc.start_date.setText(seventh);
                    rc.end_date.setText(eighth);
                    rc.days_count1.setText(ninth);
                    rc.total_amount.setText(tenth);
                    rc.setVisible(true);   
            }
        }
        jTable1.repaint();
        jTable1.revalidate();
    }//GEN-LAST:event_receiptMouseClicked

    private void ViewR_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewR_btnActionPerformed

    }//GEN-LAST:event_ViewR_btnActionPerformed

    private void Booking_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Booking_btnActionPerformed
        Main_menu mm = new Main_menu();
        mm.show();
        dispose();
    }//GEN-LAST:event_Booking_btnActionPerformed

    private void search_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_fieldActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel)this.jTable1.getModel();
        while (tableModel.getRowCount() > 0) {
            tableModel.removeRow(0);
        }
        File file = new File("file/booking.txt");
        try{
            BufferedReader br;
            br = new BufferedReader(new FileReader(file));
            String readLine;
            while((readLine = br.readLine()) != null) {
                String[] s_array = readLine.split("\n");
                for (String s : s_array) {
                    for (int i = 0; i < s_array.length; i++) {
                        String[] s_room = s.split(", ");
                        if (s_room[1].equals(search_field.getText())) {
                            int f = tableModel.getRowCount() + 1;
                            tableModel.addRow (new Object[]{f, s_room[0], s_room[1], s_room[2], s_room[3], s_room[4], s_room[5], s_room[6], s_room[7], s_room[8], s_room[9], s_room[10]});
                        }
                    }
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Modify.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modify().setVisible(true);
            }
        });
    }
    
    public void Table(){
        JButton checkout_btn = new JButton();
        checkout_btn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            }
        });
        try{
            File file = new File("file/booking.txt");
            BufferedReader br  = new BufferedReader (new FileReader(file));
            String Booking;
            int f = 0;
            while ((Booking = br.readLine())!= null){
                f++;
                String[] b_array = Booking.split("\n");
                for (String a : b_array){
                    for (int i = 0; i < b_array.length; i++) {
                        String[] b_room = a.split(", ");
                        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
                        table.addRow (new Object[]{f, b_room[0], b_room[1], b_room[2], b_room[3], b_room[4], b_room[5], b_room[6], b_room[7], b_room[8], b_room[9], b_room[10]});
                    }
                }
            }
            br.close();
        }catch(Exception e){
              System.out.print("Modify Error");    
        }
    }  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Booking_btn;
    private javax.swing.JLabel Cus_name;
    private javax.swing.JLabel Logo_pic;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JLabel Main_title;
    private javax.swing.JButton Modify_btn;
    private javax.swing.JButton Search;
    private javax.swing.JButton ViewR_btn;
    private javax.swing.JLabel adm_pic;
    private javax.swing.JButton back;
    private javax.swing.JButton checkout;
    private javax.swing.JButton delete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modify;
    private javax.swing.JButton receipt;
    private javax.swing.JTextField search_field;
    // End of variables declaration//GEN-END:variables
}
